name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - env:
        HHVM_VERSION: 4.52-latest 
    - name: Build the Docker image
      run: docker build -t hhvmcn/user-documentation:scratch -f .deploy/built-site.Dockerfile .
